### ISSUE TITLE
Error during MMSF installation

### ISSUE THREAD

**Issue by prattpratt** [St3v3nsS/MMSF#10]
I've made steps as describe in installation section
```
git clone https://github.com/St3v3nsS/MMSF.git
cd MMSF
python3 -m pip install -r requirements.txt
python3 mmsfupdate.py
```
But I'm getting the following error on  the last line:
```
username:MMSF username$ python3 mmsfupdate.py
Traceback (most recent call last):
  File "/Users/username/Workspace/MMSF/mmsfupdate.py", line 13, in <module>
    from Classes.utils import quit_app
  File "/Users/username/Workspace/MMSF/Classes/utils.py", line 6, in <module>
    from Classes.constants import Constants
  File "/Users/username/Workspace/MMSF/Classes/constants.py", line 4, in <module>
    class Constants(Enum):
  File "/Users/username/Workspace/MMSF/Classes/constants.py", line 27, in Constants
    NUCLEI = f'{os.path.join(os.environ.get("GOPATH"), "bin/nuclei")}'
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I'm using MacBook Pro 15-inch, 2018 running macOS  14.2.1.

**Comment by prattpratt** [comment]
@St3v3nsS yep, that is the problem. I think this should be added to installation steps.

**Comment by St3v3nsS** [comment]
Done. Thanks for your help!
