### ISSUE TITLE
Getting following error while updating

### ISSUE THREAD

**Issue by bhaveshraj336** [St3v3nsS/MMSF#25]
python3 mmsfupdate.py

[*] Initiating directories
[+] Installing python dependencies
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: reflutter==0.7.8 in /home/bhavesh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.7.8)
Requirement already satisfied: objection==1.11.0 in /home/bhavesh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: frida-tools==12.4.2 in /home/bhavesh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (12.4.2)
Requirement already satisfied: beautifulsoup4==4.12.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (4.12.3)
Requirement already satisfied: click==8.1.7 in /home/bhavesh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (8.1.7)
Requirement already satisfied: psutil==5.9.8 in /home/bhavesh/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (5.9.8)
Requirement already satisfied: frida>=14.0.0 in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (16.5.9)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.3 in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (3.0.43)
Requirement already satisfied: tabulate in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (0.9.0)
Requirement already satisfied: semver<3,>=2 in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (2.13.0)
Requirement already satisfied: delegator.py in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (0.1.1)
Requirement already satisfied: requests in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: flask in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: pygments in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (2.14.0)
Requirement already satisfied: litecli>=1.3.0 in /home/bhavesh/.local/lib/python3.10/site-packages (from objection==1.11.0->-r requirements.txt (line 2)) (1.13.2)
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /home/bhavesh/.local/lib/python3.10/site-packages (from frida-tools==12.4.2->-r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4==4.12.3->-r requirements.txt (line 4)) (2.6)
Requirement already satisfied: typing-extensions in /home/bhavesh/.local/lib/python3.10/site-packages (from frida>=14.0.0->objection==1.11.0->-r requirements.txt (line 2)) (4.11.0)
Requirement already satisfied: cli-helpers>=2.2.1 in /home/bhavesh/.local/lib/python3.10/site-packages (from cli-helpers[styles]>=2.2.1->litecli>=1.3.0->objection==1.11.0->-r requirements.txt (line 2)) (2.3.1)
Requirement already satisfied: configobj>=5.0.5 in /home/bhavesh/.local/lib/python3.10/site-packages (from litecli>=1.3.0->objection==1.11.0->-r requirements.txt (line 2)) (5.0.9)
Requirement already satisfied: sqlparse>=0.4.4 in /home/bhavesh/.local/lib/python3.10/site-packages (from litecli>=1.3.0->objection==1.11.0->-r requirements.txt (line 2)) (0.5.3)
Requirement already satisfied: wcwidth in /home/bhavesh/.local/lib/python3.10/site-packages (from prompt-toolkit<4.0.0,>=3.0.3->objection==1.11.0->-r requirements.txt (line 2)) (0.2.6)
Requirement already satisfied: pexpect>=4.1.0 in /usr/lib/python3/dist-packages (from delegator.py->objection==1.11.0->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: Werkzeug>=3.0.0 in /home/bhavesh/.local/lib/python3.10/site-packages (from flask->objection==1.11.0->-r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in /home/bhavesh/.local/lib/python3.10/site-packages (from flask->objection==1.11.0->-r requirements.txt (line 2)) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in /home/bhavesh/.local/lib/python3.10/site-packages (from flask->objection==1.11.0->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in /home/bhavesh/.local/lib/python3.10/site-packages (from flask->objection==1.11.0->-r requirements.txt (line 2)) (1.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/bhavesh/.local/lib/python3.10/site-packages (from requests->objection==1.11.0->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->objection==1.11.0->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->objection==1.11.0->-r requirements.txt (line 2)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->objection==1.11.0->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /home/bhavesh/.local/lib/python3.10/site-packages (from Jinja2>=3.1.2->flask->objection==1.11.0->-r requirements.txt (line 2)) (2.1.5)
[*] Checking for docker --version
[+] Installed
[*] Checking for apktool
[+] Installed
[*] Checking for java -jar /home/bhavesh/.mmsf/utils/ubersigner.jar
[+] Installed
[*] Checking for java
[+] Installed
[*] Checking for reflutter
[+] Installed
[*] Checking for objection
[+] Installed
[*] Installing 
[*] Downloading frida-server for x86
[*] Decompressing the file and installing to device
Traceback (most recent call last):
  File "/home/bhavesh/Downloads/MMSF/mmsfupdate.py", line 523, in <module>
    installer.install_packages()
  File "/home/bhavesh/Downloads/MMSF/mmsfupdate.py", line 60, in install_packages
    self._install(package)
  File "/home/bhavesh/Downloads/MMSF/mmsfupdate.py", line 78, in _install
    self._install_frida_server()
  File "/home/bhavesh/Downloads/MMSF/mmsfupdate.py", line 273, in _install_frida_server
    output = subprocess.run([Constants.ADB.value, 'shell', 'ls', '/tmp'], stderr=PIPE, stdout=DEVNULL).stderr.decode().splitlines()[0]
IndexError: list index out of range

**Comment by St3v3nsS** [comment]
Hi there, do you have ADB installed? if so, please either export it or change the path in Classes/constants.py. If this still does not work, I will try to update the tool to automatically install ADB also.
